#!/usr/bin/env python

# Copyright 2013 Craig Sprout
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import os
import pyrax

credsFile = os.path.expanduser("~/.rackspace_cloud_credentials")
pyrax.set_credential_file(credsFile)

cf = pyrax.cloudfiles
dns = pyrax.cloud_dns

cont = cf.create_container("CDN Enabled Container - Serving Content")
cf.make_container_public(cont, ttl=86400)
containerUri = cont.cdn_uri

htmlContent="""<html>
<head>
    <title>CDN Enabled Index Page</title>
</head>
<body>
<h1>This is a CDN enabled Index Page</h1>
<h2>Along with old-school, plain HTML</h2>
<h3>And headers.</h3>
</body>
</html>"""

chksum = pyrax.utils.get_checksum(htmlContent)
indexFile = cont.store_object("index.html", htmlContent, etag=chksum)


dnsRecord = [{
                "type" : "CNAME",
                "name" : "www.foobar.com",
                "data" : containerUri,
                "ttl"  : 300
                }
            ]

newDomain = dns.create(name="foobar.com", comment="Primary Domain", emailAddress="sample@example.com", records=dnsRecord)
