#!/usr/bin/env python

# Copyright 2013 Craig Sprout
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import os
import time
import pyrax

credsFile = os.path.expanduser("~/.rackspace_cloud_credentials")
pyrax.set_credential_file(credsFile)
instanceName = "newSQL"
databaseName = "newDatabase"

cdb = pyrax.cloud_databases

newInstance = cdb.create(instanceName, flavor="512MB Instance", volume=2)

while cdb.get(newInstance).status != "ACTIVE":
    time.sleep(5)

newDatabase = newInstance.create_database(databaseName)

newUser = newInstance.create_user(name="dbuser", password="pASSw3rd", database_names=[newDatabase])
