#!/usr/bin/env python

# Copyright 2013 Craig Sprout
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import os
import pyrax
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-d", "--domain", type=str, help="FQDN of record to add", required=True)
parser.add_argument("-a", "--address", type=str, help="IP address of host.", required=True)
args = parser.parse_args()

theDomain = args.domain
theAddress = args.address

credsFile = os.path.expanduser("~/.rackspace_cloud_credentials")
pyrax.set_credential_file(credsFile)

domainParts = theDomain.split(".")
domainName = domainParts[-2] + "." + domainParts[-1]

dns = pyrax.cloud_dns

dnsRecord = [{
                "type" : "A",
                "name" : theDomain,
                "data" : theAddress,
                "ttl"  : 300
                }
            ]

for domain in dns.list():
    testDomain = str(domain.name)
    if testDomain == domainName:
        subrecord = True
        myDomain  = domain
        break
    else:
        subrecord = False

if subrecord is True:
    newRecord = dns.add_record(myDomain, dnsRecord)
else:
    newDomain = dns.create(name=domainName, comment="Primary Domain", emailAddress="sample@example.com", records=dnsRecord)
